apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pythondeploy
  name: pythondeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythondeploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pythondeploy
    spec:
      containers:
      - image: selmi1999/pythonimg:latest
        name: pythonimg
        resources: {}
status: {}
