apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pythondeploy
  name: pythonservice
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5000
  selector:
    app: pythondeploy
status:
  loadBalancer: {}
